package agent

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"time"
)

// LLMClient is the interface for LLM providers (OpenAI, Claude, etc.).
type LLMClient interface {
	// GenerateCode asks the LLM to generate code for a given task context.
	GenerateCode(ctx context.Context, prompt CodePrompt) (*CodeResponse, error)
}

// CodePrompt describes a code generation request.
type CodePrompt struct {
	// Task description in natural language
	Task string
	// The file path where the code should be applied
	FilePath string
	// Language (go, python, etc.)
	Language string
	// Additional context from the codebase
	Context string
	// Constraints or requirements
	Constraints string
}

// CodeResponse contains the LLM's response for code generation.
type CodeResponse struct {
	// The generated code patch
	Patch string
	// Explanation of what was changed
	Explanation string
	// Confidence score (0-1) in the suggestion
	Confidence float64
	// Any warnings or concerns
	Warnings []string
}

// OpenAIClient implements LLMClient using the OpenAI API.
type OpenAIClient struct {
	APIKey  string
	Model   string
	BaseURL string
	Timeout time.Duration
}

// NewOpenAIClient creates an OpenAI LLM client.
// API key is read from OPENAI_API_KEY environment variable.
func NewOpenAIClient(model string) *OpenAIClient {
	apiKey := os.Getenv("OPENAI_API_KEY")
	if apiKey == "" {
		apiKey = "dummy-key-for-development"
	}
	baseURL := os.Getenv("OPENAI_BASE_URL")
	if baseURL == "" {
		baseURL = "https://api.openai.com/v1"
	}
	return &OpenAIClient{
		APIKey:  apiKey,
		Model:   model,
		BaseURL: baseURL,
		Timeout: 60 * time.Second,
	}
}

// GenerateCode implements LLMClient.
func (c *OpenAIClient) GenerateCode(ctx context.Context, prompt CodePrompt) (*CodeResponse, error) {
	if c.APIKey == "dummy-key-for-development" {
		return c.mockResponse(prompt)
	}

	systemPrompt := `You are PADS, an autonomous code improvement agent.
Your task is to generate code fixes or improvements for the given file.
Respond with a JSON object containing:
- "patch": the code changes to apply (as a full file replacement or diff)
- "explanation": brief explanation of what changed
- "confidence": your confidence level (0.0-1.0)
- "warnings": any concerns or caveats`

	userPrompt := fmt.Sprintf(`## Task
%s

## Target File
%s

## Language
%s

## Context
%s

## Constraints
%s

Generate the code change:`, prompt.Task, prompt.FilePath, prompt.Language, prompt.Context, prompt.Constraints)

	reqBody := map[string]interface{}{
		"model": c.Model,
		"messages": []map[string]string{
			{"role": "system", "content": systemPrompt},
			{"role": "user", "content": userPrompt},
		},
		"temperature": 0.3,
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, "POST", c.BaseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.APIKey)

	client := &http.Client{Timeout: c.Timeout}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("API error: status %d", resp.StatusCode)
	}

	var result struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}

	if len(result.Choices) == 0 {
		return nil, fmt.Errorf("no response from LLM")
	}

	return c.parseResponse(result.Choices[0].Message.Content, prompt)
}

// parseResponse parses the LLM's text response into a CodeResponse.
func (c *OpenAIClient) parseResponse(content string, prompt CodePrompt) (*CodeResponse, error) {
	// Try to extract JSON from the response
	var codeResp CodeResponse

	// First, try to parse the entire content as JSON
	if err := json.Unmarshal([]byte(content), &codeResp); err != nil {
		// If that fails, treat the content as the patch directly
		codeResp.Patch = content
		codeResp.Explanation = "Generated by LLM"
		codeResp.Confidence = 0.7
	}

	return &codeResp, nil
}

// mockResponse returns a mock response for development without API keys.
func (c *OpenAIClient) mockResponse(prompt CodePrompt) (*CodeResponse, error) {
	return &CodeResponse{
		Patch:       "// Mock: set OPENAI_API_KEY to enable real LLM calls",
		Explanation: fmt.Sprintf("Mock response for task: %s on %s", prompt.Task, prompt.FilePath),
		Confidence:  0.5,
		Warnings:    []string{"Running in mock mode - set OPENAI_API_KEY"},
	}, nil
}

// ClaudeClient implements LLMClient using Anthropic's Claude API.
type ClaudeClient struct {
	APIKey  string
	Model   string
	Timeout time.Duration
}

// NewClaudeClient creates a Claude LLM client.
func NewClaudeClient(model string) *ClaudeClient {
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		apiKey = "dummy-key-for-development"
	}
	return &ClaudeClient{
		APIKey:  apiKey,
		Model:   model,
		Timeout: 60 * time.Second,
	}
}

// GenerateCode implements LLMClient (placeholder for Claude).
func (c *ClaudeClient) GenerateCode(ctx context.Context, prompt CodePrompt) (*CodeResponse, error) {
	if c.APIKey == "dummy-key-for-development" {
		return &CodeResponse{
			Patch:       "// Mock: set ANTHROPIC_API_KEY to enable real LLM calls",
			Explanation: fmt.Sprintf("Mock response for task: %s", prompt.Task),
			Confidence:  0.5,
			Warnings:    []string{"Running in mock mode"},
		}, nil
	}
	return nil, fmt.Errorf("Claude API not yet implemented")
}